# Data Import

In [ ]:
import numpy as np
import pandas as pd
import nflreadpy as nfl
import matplotlib.pyplot as plt

SEASONS = [2022, 2023, 2024, 2025]
POSITIONS = ["RB", "WR", "TE"]

PBP_COLS = [
    "season", "week", "season_type", "posteam", "down", "qtr",
    "half_seconds_remaining", "yardline_100", "pass_attempt", "rush_attempt",
    "qb_kneel", "qb_spike", "receiver_player_id", "rusher_player_id",
]

stats = nfl.load_player_stats(SEASONS).to_pandas()
snaps = nfl.load_snap_counts(SEASONS).to_pandas()
players = nfl.load_players().to_pandas()
ff_ids = nfl.load_ff_playerids().to_pandas()
pbp = nfl.load_pbp(SEASONS).select(PBP_COLS).to_pandas()

print("Player stats:", stats.shape)
print("Snap counts:", snaps.shape)
print("Player metadata:", players.shape)
print("Fantasy football IDs:", ff_ids.shape)
print("Play-by-play:", pbp.shape)

Player stats: (75879, 150)
Snap counts: (106149, 16)
Player metadata: (24861, 39)
Fantasy football IDs: (12531, 35)
Play-by-play: (197362, 14)

# Look at columns

# everything down pt_out_of_bounds to before fantasy_points

In [28]:
for name, frame in [("STATS", stats), ("SNAPS", snaps), ("PLAYERS", players)]:
    print(name)
    print(frame.columns.tolist())
    display(frame.head())

STATS
['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'season', 'week', 'season_type', 'game_id', 'team', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'pacr', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'def_punt_blocks', 'def_pat_blocks', 'def_fg_blocks', 'def_2pt_atts', 'def_2pt_made', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards', 'fantasy_points', 'fantasy_points_ppr']

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,...,pt_out_of_bounds,pt_downed,pt_touchback,pt_fair_caught,pt_returned,pt_return_yards,pt_return_tds,pt_net_yards,fantasy_points,fantasy_points_ppr
0,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2022,1,REG,2022_01_TB_DAL,...,0,0,0,0,0,0,0,0,10.38,10.38
1,00-0022824,A.Lee,Andy Lee,P,SPEC,https://static.www.nfl.com/image/private/f_aut...,2022,1,REG,2022_01_KC_ARI,...,0,0,0,0,5,44,0,211,0.00,0.00
2,00-0023252,R.Gould,Robbie Gould,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2022,1,REG,2022_01_SF_CHI,...,0,0,0,0,0,0,0,0,0.00,0.00
3,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2022,1,REG,2022_01_GB_MIN,...,0,0,0,0,0,0,0,0,3.70,3.70
4,00-0023853,M.Prater,Matt Prater,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2022,1,REG,2022_01_KC_ARI,...,0,0,0,0,0,0,0,0,0.00,0.00

SNAPS
['game_id', 'pfr_game_id', 'season', 'game_type', 'week', 'player', 'pfr_player_id', 'position', 'team', 'opponent', 'offense_snaps', 'offense_pct', 'defense_snaps', 'defense_pct', 'st_snaps', 'st_pct']

,game_id,pfr_game_id,season,game_type,week,player,pfr_player_id,position,team,opponent,offense_snaps,offense_pct,defense_snaps,defense_pct,st_snaps,st_pct
0,2022_01_BAL_NYJ,202209110nyj,2022,REG,1,Max Mitchell,MitcMa02,T,NYJ,BAL,84.0,1.0,0.0,0.0,3.0,0.11
1,2022_01_BAL_NYJ,202209110nyj,2022,REG,1,Alijah Vera-Tucker,VeraAl00,G,NYJ,BAL,84.0,1.0,0.0,0.0,3.0,0.11
2,2022_01_BAL_NYJ,202209110nyj,2022,REG,1,George Fant,FantGe00,T,NYJ,BAL,84.0,1.0,0.0,0.0,3.0,0.11
3,2022_01_BAL_NYJ,202209110nyj,2022,REG,1,Laken Tomlinson,TomlLa01,G,NYJ,BAL,84.0,1.0,0.0,0.0,3.0,0.11
4,2022_01_BAL_NYJ,202209110nyj,2022,REG,1,Connor McGovern,McGoCo00,C,NYJ,BAL,84.0,1.0,0.0,0.0,0.0,0.00

PLAYERS
['gsis_id', 'display_name', 'common_first_name', 'first_name', 'last_name', 'short_name', 'football_name', 'suffix', 'esb_id', 'nfl_id', 'pfr_id', 'pff_id', 'otc_id', 'espn_id', 'smart_id', 'birth_date', 'position_group', 'position', 'ngs_position_group', 'ngs_position', 'height', 'weight', 'headshot', 'college_name', 'college_conference', 'jersey_number', 'rookie_season', 'last_season', 'latest_team', 'status', 'ngs_status', 'ngs_status_short_description', 'years_of_experience', 'pff_position', 'pff_status', 'draft_year', 'draft_round', 'draft_pick', 'draft_team']

,gsis_id,display_name,common_first_name,first_name,last_name,short_name,football_name,suffix,esb_id,nfl_id,...,status,ngs_status,ngs_status_short_description,years_of_experience,pff_position,pff_status,draft_year,draft_round,draft_pick,draft_team
0,00-0028830,Isaako Aaitui,Isaako,Isaako,Aaitui,NaN,NaN,NaN,AAI622937,NaN,...,DEV,NaN,NaN,2,DI,NaN,NaN,NaN,NaN,NaN
1,00-0038389,Israel Abanikanda,Israel,Israel,Abanikanda,I.Abanikanda,Israel,NaN,ABA159567,56008,...,DEV,DEV,Practice Squad,3,HB,A,2023.0,5.0,143.0,NYJ
2,00-0024644,Jon Abbate,Jon,Jon,Abbate,NaN,NaN,NaN,ABB051371,NaN,...,RES,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
3,ABB498348,Vince Abbott,Vince,Vincent,Abbott,NaN,NaN,NaN,ABB498348,NaN,...,ACT,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,00-0031021,Jared Abbrederis,Jared,Jared,Abbrederis,J.Abbrederis,Jared,NaN,ABB650964,41405,...,CUT,CUT,NaN,4,WR,NaN,2014.0,5.0,176.0,GB

# Filter and Standardize

In [29]:
TEAM_ALIASES = {"LA": "LAR", "STL": "LAR", "SD": "LAC", "OAK": "LV"}

stats_reg = stats.loc[stats["season_type"] == "REG"].copy()
snaps_reg = snaps.loc[snaps["game_type"] == "REG"].copy()
pbp_reg = pbp.loc[pbp["season_type"] == "REG"].copy()

stats_reg["team"] = stats_reg["team"].replace(TEAM_ALIASES)
snaps_reg["team"] = snaps_reg["team"].replace(TEAM_ALIASES)
pbp_reg["posteam"] = pbp_reg["posteam"].replace(TEAM_ALIASES)

stats_reg[["targets", "carries"]] = stats_reg[["targets", "carries"]].fillna(0)

# Add up the team totals

In [30]:
team_totals = (
    stats_reg
    .groupby(["season", "week", "team"], as_index=False)
    [["targets", "carries"]]
    .sum()
    .rename(columns={"targets": "team_targets", "carries": "team_carries"})
)
team_totals["team_opportunities"] = (
    team_totals["team_targets"] + team_totals["team_carries"]
)

display(team_totals.head())

   season  week team  team_targets  team_carries  team_opportunities
0    2022     1  ARI            36            22                  58
1    2022     1  ATL            32            38                  70
2    2022     1  BAL            29            21                  50
3    2022     1  BUF            31            25                  56
4    2022     1  CAR            26            19                  45

# Passing-down and red-zone counts (lowkey a lot)

In [ ]:
plays = pbp_reg.loc[
    pbp_reg["posteam"].notna()
    & (pbp_reg["qb_kneel"].fillna(0) == 0)
    & (pbp_reg["qb_spike"].fillna(0) == 0)
].copy()

plays["is_passdown"] = (
    (plays["down"].fillna(0) >= 3)
    | (plays["qtr"].isin([2, 4]) & (plays["half_seconds_remaining"].fillna(9999) <= 120))
).astype(int)
plays["is_redzone"] = (plays["yardline_100"].fillna(100) <= 20).astype(int)

keep = ["season", "week", "posteam", "is_passdown", "is_redzone"]

target_events = (
    plays.loc[(plays["pass_attempt"] == 1) & plays["receiver_player_id"].notna(),
              keep + ["receiver_player_id"]]
    .rename(columns={"posteam": "team", "receiver_player_id": "gsis_id"})
)
carry_events = (
    plays.loc[(plays["rush_attempt"] == 1) & plays["rusher_player_id"].notna(),
              keep + ["rusher_player_id"]]
    .rename(columns={"posteam": "team", "rusher_player_id": "gsis_id"})
)
events = pd.concat([target_events, carry_events], ignore_index=True)

team_sit = (
    events
    .groupby(["season", "week", "team"], as_index=False)
    .agg(
        pbp_team_opportunities=("gsis_id", "size"),
        team_passdown=("is_passdown", "sum"),
        team_redzone=("is_redzone", "sum"),
    )
)
player_sit = (
    events
    .groupby(["season", "week", "team", "gsis_id"], as_index=False)
    .agg(
        player_passdown=("is_passdown", "sum"),
        player_redzone=("is_redzone", "sum"),
    )
)

display(team_sit.head())

   season  week team  pbp_team_opportunities  team_passdown  team_redzone
0    2022     1  ARI                      59             22             9
1    2022     1  ATL                      70             22             9
2    2022     1  BAL                      48             14             6
3    2022     1  BUF                      55             11             6
4    2022     1  CAR                      44             16             8

# Check for totals against pbp totals

In [32]:
opp_check = team_totals.merge(team_sit, on=["season", "week", "team"], how="outer", indicator=True)
print(opp_check["_merge"].value_counts())

opp_check["gap"] = opp_check["team_opportunities"] - opp_check["pbp_team_opportunities"]
print(opp_check["gap"].describe())
print("Share of team-games with any gap:", (opp_check["gap"].fillna(0) != 0).mean().round(3))

_merge
both          2174
left_only        0
right_only       0
Name: count, dtype: int64
count    2174.000000
mean        0.554738
std         1.186864
min        -4.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         6.000000
Name: gap, dtype: float64
Share of team-games with any gap: 0.515

# Link the player ID's

In [33]:
id_map = (
    players[["pfr_id", "gsis_id"]]
    .dropna(subset=["pfr_id", "gsis_id"])
    .drop_duplicates(subset="pfr_id")
    .rename(columns={"pfr_id": "pfr_player_id", "gsis_id": "player_id"})
)

skill_snaps = snaps_reg.loc[
    snaps_reg["position"].isin(POSITIONS)
    & (snaps_reg["offense_snaps"] > 0)
].copy()

skill_snaps = skill_snaps.merge(
    id_map,
    on="pfr_player_id",
    how="left",
    validate="many_to_one",
)

match_rate = skill_snaps["player_id"].notna().mean()
print(f"ID match rate: {match_rate:.4f}  (prototype: 0.997)")

unmatched = (
    skill_snaps.loc[skill_snaps["player_id"].isna(), ["player", "position", "pfr_player_id"]]
    .value_counts()
    .reset_index(name="games")
)
display(unmatched.head(20))

assert match_rate >= 0.99, "ID match rate dropped below 99%. Inspect the table above."

print("Dropping unmatched player-games:", skill_snaps["player_id"].isna().sum())
skill_snaps = skill_snaps.dropna(subset=["player_id"])

ID match rate: 0.9983  (prototype: 0.997)

                player position pfr_player_id  games
0      Rodney Williams       TE      WillRo08     15
1           Cody White       WR      WhitCo05     14
2  John Samuel Shenker       TE      ShenJo00      7
3        Nathan Carter       RB      CartNa00      4

Dropping unmatched player-games: 40

# Join snaps to stats and team totals

In [34]:
join_keys = ["player_id", "season", "week", "team"]

weekly_usage = skill_snaps.merge(
    stats_reg[join_keys + ["targets", "carries"]],
    on=join_keys,
    how="left",
    validate="one_to_one",
    indicator=True,
)

display(
    weekly_usage.loc[
        weekly_usage["_merge"] == "left_only",
        ["player", "season", "week", "team"],
    ].head(20)
)
print("Player-games with no stats row:", (weekly_usage["_merge"] == "left_only").sum())

weekly_usage[["targets", "carries"]] = weekly_usage[["targets", "carries"]].fillna(0)

weekly_usage = weekly_usage.drop(columns="_merge").merge(
    team_totals,
    on=["season", "week", "team"],
    how="left",
    validate="many_to_one",
)

assert weekly_usage["team_opportunities"].notna().all(), "Some team totals did not match."

              player  season  week team
7        C.J. Uzomah    2022     1  NYJ
9         Jeff Smith    2022     1  NYJ
16       Josh Oliver    2022     1  BAL
28    Brycen Hopkins    2022     1  LAR
37      Jake Kumerow    2022     1  BUF
38     Tommy Sweeney    2022     1  BUF
56        David Bell    2022     1  CLE
58       Jesse James    2022     1  CLE
68      Dareke Young    2022     1  SEA
95    Marcedes Lewis    2022     1   GB
119     Jelani Woods    2022     1  IND
130      Dyami Brown    2022     1  WAS
138   Chris Manhertz    2022     1  JAX
139       Dan Arnold    2022     1  JAX
141    Jamycal Hasty    2022     1  JAX
142        Tim Jones    2022     1  JAX
143     Luke Farrell    2022     1  JAX
151    Maxx Williams    2022     1  ARI
153  Andre Baccellia    2022     1  ARI
182    Foster Moreau    2022     1   LV

Player-games with no stats row: 3116

# Compute the usage shares

In [35]:
weekly_usage = weekly_usage.rename(columns={
    "player": "player_name",
    "player_id": "gsis_id",
    "offense_pct": "snap_pct",
})

weekly_usage["opportunities"] = weekly_usage["targets"] + weekly_usage["carries"]

# `.where(den > 0)` gives NaN (not 0) when the team had none of that play type.
weekly_usage["target_share"] = weekly_usage["targets"] / weekly_usage["team_targets"].where(weekly_usage["team_targets"] > 0)
weekly_usage["carry_share"] = weekly_usage["carries"] / weekly_usage["team_carries"].where(weekly_usage["team_carries"] > 0)
weekly_usage["opp_share"] = weekly_usage["opportunities"] / weekly_usage["team_opportunities"].where(weekly_usage["team_opportunities"] > 0)

# Situational shares from play-by-play.
weekly_usage = (
    weekly_usage
    .merge(player_sit, on=["season", "week", "team", "gsis_id"], how="left")
    .merge(team_sit[["season", "week", "team", "team_passdown", "team_redzone"]],
           on=["season", "week", "team"], how="left")
)
weekly_usage[["player_passdown", "player_redzone"]] = weekly_usage[["player_passdown", "player_redzone"]].fillna(0)

weekly_usage["passdown_share"] = weekly_usage["player_passdown"] / weekly_usage["team_passdown"].where(weekly_usage["team_passdown"] > 0)
weekly_usage["redzone_share"] = weekly_usage["player_redzone"] / weekly_usage["team_redzone"].where(weekly_usage["team_redzone"] > 0)

weekly_usage = weekly_usage[
    [
        "season", "week", "team", "opponent", "gsis_id", "pfr_player_id",
        "player_name", "position", "offense_snaps",
        "snap_pct", "targets", "carries", "team_opportunities",
        "target_share", "carry_share", "opp_share",
        "passdown_share", "redzone_share",
    ]
].sort_values(["player_name", "season", "week"]).reset_index(drop=True)

display(weekly_usage.head(10))

,season,week,team,opponent,gsis_id,pfr_player_id,player_name,position,offense_snaps,snap_pct,targets,carries,team_opportunities,target_share,carry_share,opp_share,passdown_share,redzone_share
0,2022,1,PHI,DET,00-0035676,BrowAJ00,A.J. Brown,WR,67.0,0.87,13.0,0.0,68,0.448276,0.0,0.191176,0.192308,0.153846
1,2022,2,PHI,MIN,00-0035676,BrowAJ00,A.J. Brown,WR,64.0,0.88,8.0,0.0,65,0.258065,0.0,0.123077,0.111111,0.000000
2,2022,3,PHI,WAS,00-0035676,BrowAJ00,A.J. Brown,WR,56.0,0.80,10.0,0.0,64,0.294118,0.0,0.156250,0.230769,0.214286
3,2022,4,PHI,JAX,00-0035676,BrowAJ00,A.J. Brown,WR,70.0,0.85,7.0,0.0,74,0.291667,0.0,0.094595,0.136364,0.000000
4,2022,5,PHI,ARI,00-0035676,BrowAJ00,A.J. Brown,WR,54.0,0.74,7.0,0.0,67,0.205882,0.0,0.104478,0.076923,0.117647
5,2022,6,PHI,DAL,00-0035676,BrowAJ00,A.J. Brown,WR,61.0,0.86,8.0,0.0,61,0.363636,0.0,0.131148,0.250000,0.200000
6,2022,8,PHI,PIT,00-0035676,BrowAJ00,A.J. Brown,WR,39.0,0.68,10.0,0.0,50,0.333333,0.0,0.200000,0.066667,0.000000
7,2022,9,PHI,HOU,00-0035676,BrowAJ00,A.J. Brown,WR,56.0,0.86,6.0,0.0,56,0.240000,0.0,0.107143,0.125000,0.125000
8,2022,10,PHI,WAS,00-0035676,BrowAJ00,A.J. Brown,WR,39.0,0.78,4.0,0.0,45,0.160000,0.0,0.088889,0.200000,0.000000
9,2022,11,PHI,IND,00-0035676,BrowAJ00,A.J. Brown,WR,60.0,0.88,7.0,0.0,56,0.304348,0.0,0.125000,0.000000,0.090909

# Save the tables

In [13]:
weekly_usage.to_parquet("weekly_usage.parquet", index=False)
weekly_usage.to_csv("weekly_usage.csv", index=False)